import { Project, ProjectType } from './index.d';

export const projects: Project[] = [
  {
    name: 'Portfolio Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['TypeScript', 'Next.js', 'Tailwind CSS'],
    picture: 'webPortofolio.jpg',
    // repoLink: 'https://github.com/Syaiful-Maulana/Web-Portofolio',
  },
  {
    name: 'Loak.ID Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['React.JS', 'Node.JS', 'Bootstrap', 'Express.Js', 'Redux'],
    picture: 'loakid.jpg',
    // repoLink: 'https://github.com/Syaiful-Maulana/loakId',
  },
  {
    name: 'DapurFresh Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['React.JS', 'Bootstrap', 'Tailwind', 'Express.Js', 'Redux'],
    picture: 'dapur.jpg',
    // repoLink: 'https://github.com/Syaiful-Maulana/dapurfresh',
  },
  {
    name: 'Easybus Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'Laravel', 'MySQL', 'Bootstrap', 'Firebase', 'Midtrans'],
    picture: 'easybus.jpg',
    // repoLink: '#',
  },
  {
    name: 'Sistem Pakar Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'CodeIgniter', 'MySQL', 'Bootstrap', 'Wablas'],
    picture: 'sispak.jpg',
    // repoLink: '#',
  },
  {
    name: 'Sistem Pakar Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'CodeIgniter', 'MySQL', 'Bootstrap'],
    picture: 'sispaktiktok.jpg',
    // repoLink: '#',
  },
  {
    name: 'Posyandu Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'Laravel', 'MySQL', 'Bootstrap', 'Wablas'],
    picture: 'posyandu.jpg',
    // repoLink: '#',
  },
  {
    name: 'Lelang Tanah Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'Native', 'MySQL', 'Bootstrap'],
    picture: 'silelang.jpg',
    // repoLink: '#',
  },
  {
    name: 'Management Bansos Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'Laravel', 'MySQL', 'Bootstrap'],
    picture: 'bansos.jpg',
    // repoLink: '#',
  },
  {
    name: 'SPK Topsis Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'Native', 'MySQL', 'Bootstrap'],
    picture: 'milihhp.jpg',
    // repoLink: '#',
  },
  {
    name: 'Point Pelanggaran Siswa Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'Laravel', 'MySQL', 'Bootstrap'],
    picture: 'pointpelanggaran.jpg',
    // repoLink: '#',
  },
  {
    name: 'POS Apotek Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['PHP', 'Laravel', 'MySQL', 'Bootstrap'],
    picture: 'apotek.jpg',
    // repoLink: '#',
  },

  {
    name: 'Klasement Sepak Bola API',
    description: 'REST API ',
    type: ProjectType.API,
    tags: ['NodeJS', 'ExpressJs', 'SequelizeJs', 'MongoDB'],
    picture: 'bola.jpg',
    // repoLink: 'https://github.com/Syaiful-Maulana/api-invoice',
  },
  {
    name: 'Pinjam Buku API',
    description: 'REST API ',
    type: ProjectType.API,
    tags: ['Golang', 'ECHO', 'GORM', 'PostgreSQL'],
    picture: 'pinjamapi.jpg',
    // repoLink: 'https://github.com/Syaiful-Maulana/api-invoice',
  },
  {
    name: 'Invoice API',
    description: 'REST API ',
    type: ProjectType.API,
    tags: ['Golang', 'ECHO', 'GORM'],
    picture: 'invoice.jpg',
    // repoLink: 'https://github.com/Syaiful-Maulana/api-invoice',
  },
  {
    name: 'DapurFresh API',
    description: 'REST API ',
    type: ProjectType.API,
    tags: ['NodesJs', 'ExpressJs', 'Sequelize', 'PostgreSQL'],
    picture: 'dapurbe.jpg',
    // repoLink: 'https://github.com/Syaiful-Maulana/api-dapurfresh',
  },
  {
    name: 'Loak ID API',
    description: 'REST API ',
    type: ProjectType.API,
    tags: ['NodesJs', 'ExpressJs', 'Sequelize', 'PostgreSQL'],
    picture: 'loakidbe.jpg',
    // repoLink: '#',
  },
  {
    name: 'Games API',
    description: 'REST API ',
    type: ProjectType.API,
    tags: ['NodesJs', 'ExpressJs', 'Sequelize', 'PostgreSQL'],
    picture: 'apiGame.jpg',
    // repoLink: '#',
  },
];
